name: Run daily_5k daily

on:
  schedule:
    - cron: "0 3 * * *"  # every day at 03:00 UTC
  workflow_dispatch:      # so you can also run it manually from GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow this job to push commits back to the repo

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #get full history so we can pull/rebace
          ref: main #make sure we're on main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run players_stats.py
        run: |
          python core/scripts/players_stats_5k.py

      - name: Commit and push updated data
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Check if anything in data/ changed
          if [ -n "$(git status --porcelain core/data)" ]; then
            echo "Changes detected in core/data/, committing..."
            git add core/data
            git commit -m "Update data from players_stats.py [skip ci]" || echo "Nothing to commit"

            echo "Fetching latest main frmo origin..."
            git fetch origin main

            echo "Rebasing on top of origin/main..."
            git pull --rebase origin main

            echo "Pushing changes to origin/main..."
            git push origin HEAD:main
          else
            echo "No changes in core/data/ directory."
          fi
